from dotenv import load_dotenv
from os import getenv
from enum import Enum
from redis import Redis

load_dotenv()

class ClassificationName(Enum):
    NOGA = "NOGA"
    ATR = "ATR"
    WINDCOAT = "WINDCOAT"
    AT = "AT"


class Random16DigitID(Enum):
    ONE_NUMBER = 3001697090449141
    SECOND_NUMBER = 13533879590735665
    THIRD_NUMBER = 1691298520696870

class FastAPIConstants(Enum):
    ALL_DETECTIONS = 0
    CRITICAL_DETECTIONS = 1

DELAY_SECONDS = 1
NANOSECONDS_CONVERSION_TO_SECONDS = 1_000_000_000
TRUELY_RANDOM_16_DIGIT_ID_START_VAR = 1000000000000000
TRUELY_RANDOM_16_DIGIT_ID_END_VAR = 9999999999999999
QOS_FILE = "rticonnector/Configuration/BarakQosProfile.xml"
CHANCE_FOR_ID = 0.5
ENGINE_STRING = "TRUNCATE TABLE detections RESTART IDENTITY"
DATABASE_URL_DEFAULT = "postgresql+psycopg2://postgres:postgres@localhost:5432/dds_project"
DATABASE_URL = getenv("DATABASE_URL", DATABASE_URL_DEFAULT)
DEFAULT_SYSTEM_MOD_VARIABLE = FastAPIConstants.CRITICAL_DETECTIONS.value
DETECTION_SOURCEID_PLATFORMID = 1
DETECTION_SOURCEID_SYSTEMID = 14
DETECTION_SOURCEID_MODULEID = 9
FASPTAPI_SERVER_HOST = "127.0.0.1"
FASPTAPI_SERVER_PORT = 8000
CHOSEN_SYSTEM_MOD_VARIABLE_FILTERS = 1
REDIS_CLIENT = Redis(
    host = "localhost",
    port = 6379,
    decode_responses = False,
)


