import enum


class MiscellaneousEnum(enum.IntEnum):
    VERY_SHORT_STRING = 10
    SHORT_STRING = 20
    MEDIUM_STRING = 100
    LONG_STRING_256 = 256
    LONG_STRING = 500
    DDS_SAMPLE_INFO = 36
    METHODS_COUNT = 15
    DETECTION_METHODS = 32
