module P_LDM_Common {
    typedef long T_Int32;

    typedef short T_Int16;

    struct T_Identifier {
        T_Int32 A_platformId;    //@ID 193125732
        T_Int16 A_systemId;    //@ID 226945837
        T_Int16 A_moduleId;    //@ID 98483598
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef long long T_Int64;

    struct T_DateTime {
        T_Int64 A_seconds;    //@ID 47523875
        T_Int32 A_nanoseconds;    //@ID 168751860
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef char T_Char;

    typedef sequence<P_LDM_Common::T_Char,20> T_ShortString;

    typedef sequence<P_LDM_Common::T_Char,500> T_LongString;

    typedef unsigned long T_UInt32;

    struct T_Duration {
        T_UInt32 A_seconds;    //@ID 47523875
        T_UInt32 A_nanoseconds;    //@ID 168751860
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef unsigned short T_UInt16;

    struct T_Version {
        T_UInt16 A_major;    //@ID 181829708
        T_UInt16 A_minor;    //@ID 123566980
        T_UInt16 A_revision;    //@ID 120131913
        T_UInt16 A_build;    //@ID 132241162
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef sequence<P_LDM_Common::T_Char,10> T_VeryShortString;

}; // end of 'P_LDM_Common' module

module P_Maintenance_PSM {
    struct C_Resource_Specification {
        P_LDM_Common::T_Identifier A_sourceID; //@key
    //@ID 118386796
        P_LDM_Common::T_DateTime A_timeOfDataGeneration;    //@ID 234062147
        P_LDM_Common::T_ShortString A_resourceTypeName;    //@ID 78356829
        P_LDM_Common::T_LongString A_descriptor;    //@ID 52732520
        P_LDM_Common::T_DateTime A_creationDate;    //@ID 194068903
        P_LDM_Common::T_DateTime A_restorationDate;    //@ID 158268010
        P_LDM_Common::T_DateTime A_softwareUpdateDate;    //@ID 264688042
        P_LDM_Common::T_DateTime A_hardwareUpdateDate;    //@ID 228270743
        P_LDM_Common::T_ShortString A_companyCode;    //@ID 74190848
        P_LDM_Common::T_ShortString A_restorerCode;    //@ID 111274484
        P_LDM_Common::T_ShortString A_projectCode;    //@ID 202378202
        P_LDM_Common::T_Duration A_totalOpTime;    //@ID 259762017
        P_LDM_Common::T_Version A_softwareVersion;    //@ID 240315737
        P_LDM_Common::T_Version A_hardwareVersion;    //@ID 200278849
        P_LDM_Common::T_VeryShortString A_catalogCode;    //@ID 211890284
        P_LDM_Common::T_VeryShortString A_serialNumber;    //@ID 57564667
        sequence<P_LDM_Common::T_Identifier,5> A_includedSoftwareSourceID;    //@ID 45603233
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

}; // end of 'P_Maintenance_PSM' module

