module P_LDM_Common {
    typedef long T_Int32;

    typedef short T_Int16;

    struct T_Identifier {
        T_Int32 A_platformId;    //@ID 193125732
        T_Int16 A_systemId;    //@ID 226945837
        T_Int16 A_moduleId;    //@ID 98483598
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef long long T_Int64;

    struct T_DateTime {
        T_Int64 A_seconds;    //@ID 47523875
        T_Int32 A_nanoseconds;    //@ID 168751860
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    enum T_EnabledState {
        @default_literal
        L_EnabledState_ENABLED = 0,
        L_EnabledState_DISABLED = 1
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

    typedef double T_Double;

    typedef octet T_Byte;

}; // end of 'P_LDM_Common' module

module P_Tactical_Sensor_PSM {
    struct C_Tactical_Sensor {
        P_LDM_Common::T_Identifier A_sourceID; //@key
    //@ID 118386796
        P_LDM_Common::T_DateTime A_timeOfDataGeneration;    //@ID 234062147
        P_LDM_Common::T_EnabledState A_sensorCurrentStatus;    //@ID 219859602
        P_LDM_Common::T_Double A_falseAlarmProbability;    //@ID 3141405
        P_LDM_Common::T_Double A_detectionProbability;    //@ID 229637417
        P_LDM_Common::T_Byte A_sensitivityLevel; //@Optional
    //@ID 175470000
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

}; // end of 'P_Tactical_Sensor_PSM' module

