module P_LDM_Common {
    typedef long T_Int32;

    typedef short T_Int16;

    struct T_Identifier {
        T_Int32 A_platformId;    //@ID 193125732
        T_Int16 A_systemId;    //@ID 226945837
        T_Int16 A_moduleId;    //@ID 98483598
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef long long T_Int64;

    struct T_DateTime {
        T_Int64 A_seconds;    //@ID 47523875
        T_Int32 A_nanoseconds;    //@ID 168751860
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef unsigned long long T_UInt64;

    struct T_Uuid {
        T_UInt64 A_msb;    //@ID 21731089
        T_UInt64 A_lsb;    //@ID 16396169
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef double T_Double;

    typedef T_Double T_Percentage;

    typedef char T_Char;

    typedef sequence<P_LDM_Common::T_Char,20> T_ShortString;

}; // end of 'P_LDM_Common' module

module P_Tactical_Sensor_PSM {
    enum T_IFFCategory {
        @default_literal
        L_IFFCategory_UNKNOWN = 0,
        L_IFFCategory_FRIEND = 1,
        L_IFFCategory_FOE = 2,
        L_IFFCategory_UNINVOLVED = 3
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

    enum T_EngagementStatus {
        @default_literal
        L_EngagementStatus_UNKNOWN = 0,
        L_EngagementStatus_NONE = 1,
        L_EngagementStatus_HANDLED = 2,
        L_EngagementStatus_DROPPED = 3,
        L_EngagementStatus_THRETENING = 4
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

    enum T_Interception {
        @default_literal
        L_Interception_UNKNOWN = 0,
        L_Interception_ON = 1,
        L_Interception_MISSING_OUT = 2
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

    enum T_DetectionState {
        @default_literal
        L_DetectionState_NONE = 0,
        L_DetectionState_VALID_RECOGNIZED = 1,
        L_DetectionState_VALID_NOT_RECOGNIZED = 2,
        L_DetectionState_DELETED = 3,
        L_DetectionState_CANCELED = 4,
        L_DetectionState_MERGED = 5,
        L_DetectionState_SPLIT = 6,
        L_DetectionState_DESTROYED = 7
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

    enum T_DetectionType {
        @default_literal
        L_DetectionType_DETECTION = 0,
        L_DetectionType_THREAT = 1,
        L_DetectionType_TARGET = 2
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

}; // end of 'P_Tactical_Sensor_PSM' module

module P_LDM_Common {
    typedef unsigned long T_UInt32;

    struct T_Duration {
        T_UInt32 A_seconds;    //@ID 47523875
        T_UInt32 A_nanoseconds;    //@ID 168751860
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

}; // end of 'P_LDM_Common' module

module P_Tactical_Sensor_PSM {
    enum T_Trajectory {
        @default_literal
        L_Trajectory_UNKNOWN = 0,
        L_Trajectory_SURFACE = 1,
        L_Trajectory_HORIZON = 2,
        L_Trajectory_BALISTIC = 3,
        L_Trajectory_STEEP = 4,
        L_Trajectory_UNDERNEATH = 5
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

    enum T_Sensing_Method {
        @default_literal
        L_Sensing_Method_UNKNOWN = 0,
        L_Sensing_Method_RF = 1,
        L_Sensing_Method_OPTIC = 2,
        L_Sensing_Method_ACOUSTIC = 3,
        L_Sensing_Method_C4I = 4,
        L_Sensing_Method_OPERATOR = 5
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

}; // end of 'P_Tactical_Sensor_PSM' module

module P_LDM_Common {
    typedef boolean T_Boolean;

    typedef T_Double T_AngleInRadians;

    typedef T_Double T_DistanceInMeters;

    struct T_CoordinatePolar3D {
        T_AngleInRadians A_elevation;    //@ID 185059946
        T_AngleInRadians A_azimuth;    //@ID 132319399
        T_DistanceInMeters A_range;    //@ID 149142522
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef T_DistanceInMeters T_Altitude;

    typedef T_AngleInRadians T_Latitude;

    typedef T_AngleInRadians T_Longitude;

    struct T_Coordinate3D {
        T_Altitude A_altitude;    //@ID 143806669
        T_Latitude A_latitude;    //@ID 252288645
        T_Longitude A_longitude;    //@ID 249776067
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    struct T_Vector_3D {
        T_AngleInRadians A_elevation;    //@ID 185059946
        T_AngleInRadians A_azimuth;    //@ID 132319399
        T_Double A_magnitude;    //@ID 178695539
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef T_Double T_SpeedInMetPerSec;

}; // end of 'P_LDM_Common' module

module P_Tactical_Sensor_PSM {
    struct T_Field_Of_View {
        P_LDM_Common::T_AngleInRadians A_hfov;    //@ID 219673437
        P_LDM_Common::T_AngleInRadians A_vfov;    //@ID 94953845
        P_LDM_Common::T_CoordinatePolar3D A_fovCenter;    //@ID 86166626
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    struct T_Physical_Parameters {
        P_LDM_Common::T_CoordinatePolar3D A_relativeLocationsBase;    //@ID 202129906
        P_LDM_Common::T_Boolean A_sensorInertialLocationAvailable;    //@ID 160154763
        P_LDM_Common::T_Coordinate3D A_sensorInertialLocation;    //@ID 25381208
        P_LDM_Common::T_Boolean A_relativeLocationAvailable;    //@ID 247777497
        P_LDM_Common::T_Boolean A_rangeAvailable;    //@ID 260167579
        P_LDM_Common::T_CoordinatePolar3D A_relativeLocation;    //@ID 176177253
        P_LDM_Common::T_CoordinatePolar3D A_relativeLocationAccuracy;    //@ID 256823903
        P_LDM_Common::T_Boolean A_inertialLocationAvailable;    //@ID 239505011
        P_LDM_Common::T_CoordinatePolar3D A_inertialLocation;    //@ID 199017188
        P_LDM_Common::T_CoordinatePolar3D A_inertialLocationAccuracy;    //@ID 151609059
        P_LDM_Common::T_Boolean A_absoluteLocationAvailable;    //@ID 237173483
        P_LDM_Common::T_Coordinate3D A_absoluteLocation;    //@ID 126442216
        P_LDM_Common::T_Coordinate3D A_absoluteLocationAccuracy;    //@ID 29155565
        P_LDM_Common::T_Boolean A_angularVelocityAvailable;    //@ID 90633880
        P_LDM_Common::T_Vector_3D A_angularVelocity;    //@ID 41912237
        P_LDM_Common::T_Vector_3D A_angularVelocityAccuracy;    //@ID 259421538
        P_LDM_Common::T_Boolean A_linearSpeedAvailable;    //@ID 17206948
        P_LDM_Common::T_SpeedInMetPerSec A_linearSpeed;    //@ID 79564538
        P_LDM_Common::T_CoordinatePolar3D A_speedOrientation;    //@ID 105149909
        P_LDM_Common::T_SpeedInMetPerSec A_linearSpeedAccuracy;    //@ID 140233796
        P_LDM_Common::T_Boolean A_radialVelocityAvailable;    //@ID 30429412
        P_LDM_Common::T_SpeedInMetPerSec A_radialVelocity;    //@ID 218586043
        P_LDM_Common::T_SpeedInMetPerSec A_radialVelocityAccuracy;    //@ID 12645927
        P_LDM_Common::T_Boolean A_tangentialVelocityAvailable;    //@ID 206873348
        P_LDM_Common::T_SpeedInMetPerSec A_horizontalTangentialVelocity;    //@ID 195513788
        P_LDM_Common::T_SpeedInMetPerSec A_horizontalTangentialVelocityError;    //@ID 156366719
        P_LDM_Common::T_SpeedInMetPerSec A_verticalTangentialVelocity;    //@ID 194277054
        P_LDM_Common::T_SpeedInMetPerSec A_verticalTangentialVelocityError;    //@ID 201403017
        P_LDM_Common::T_Boolean A_fieldOfViewAvailable;    //@ID 158004688
        T_Field_Of_View A_fieldOfView;    //@ID 163011555
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

}; // end of 'P_Tactical_Sensor_PSM' module

module P_LDM_Common {
    typedef T_ShortString T_Descriptor;

    struct T_Dimension {
        T_Double A_height;    //@ID 126938091
        T_Double A_length;    //@ID 268122242
        T_Double A_width;    //@ID 216631209
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    enum T_Value_Source {
        @default_literal
        L_Value_Source_UNKNOWN = 0,
        L_Value_Source_CALCULATED = 1,
        L_Value_Source_MEASURED = 2,
        L_Value_Source_REPORTED = 3
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

}; // end of 'P_LDM_Common' module

module P_Tactical_Sensor_PSM {
    struct T_Descriptive_Parameters {
        sequence<P_LDM_Common::T_Descriptor,10> A_recognizingDetectorTypes;    //@ID 164911381
        P_LDM_Common::T_Boolean A_classificationAvailable;    //@ID 74505323
        P_LDM_Common::T_Descriptor A_objectClassification;    //@ID 186028223
        P_LDM_Common::T_Percentage A_classificationConfidence;    //@ID 193401693
        P_LDM_Common::T_CoordinatePolar3D A_detectionSampleSize;    //@ID 238759197
        P_LDM_Common::T_Dimension A_absoluteSize;    //@ID 141075497
        P_LDM_Common::T_Duration A_exposureDuration;    //@ID 40368954
        P_LDM_Common::T_Value_Source A_rangeMethod;    //@ID 127229930
        P_LDM_Common::T_Coordinate3D A_sourceLocationAccuracy;    //@ID 9859942
        P_LDM_Common::T_Coordinate3D A_sourceLocation;    //@ID 121402085
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    struct T_Spatial_Info {
        T_Physical_Parameters A_physicalInfo;    //@ID 170544614
        T_Descriptive_Parameters A_descriptiveInfo;    //@ID 219430159
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    enum T_SuspensionCause {
        @default_literal
        L_SuspensionCause_NOT_SUSPENDED = 0,
        L_SuspensionCause_UNKNOWN = 1,
        L_SuspensionCause_FALSE_DETECTION = 2,
        L_SuspensionCause_LATE_DETECTION = 3,
        L_SuspensionCause_IRRELEVANT = 4,
        L_SuspensionCause_BUSY = 5,
        L_SuspensionCause_VANISHED = 6,
        L_SuspensionCause_OPERATOR_DECISION = 7
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

}; // end of 'P_Tactical_Sensor_PSM' module

module P_LDM_Common {
    typedef octet T_Byte;

}; // end of 'P_LDM_Common' module

module P_Tactical_Sensor_PSM {
    struct T_DetectingMethod {
        P_LDM_Common::T_Descriptor A_detectorType;    //@ID 81702893
        P_LDM_Common::T_Descriptor A_algorithm;    //@ID 156910574
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    struct C_Detection {
        P_LDM_Common::T_Identifier A_sourceID; //@key
    //@ID 118386796
        P_LDM_Common::T_DateTime A_timeOfDataGeneration;    //@ID 234062147
        P_LDM_Common::T_Uuid A_detectionUniqueID; //@key
    //@ID 246744424
        P_LDM_Common::T_Percentage A_confidence;    //@ID 136595483
        P_LDM_Common::T_ShortString A_detectionClassification;    //@ID 85099305
        P_LDM_Common::T_Percentage A_detectionClassScore;    //@ID 76917289
        T_IFFCategory A_detectionForceType;    //@ID 180790050
        T_EngagementStatus A_detectionThreatStatus;    //@ID 223270006
        T_Interception A_interception;    //@ID 115597617
        T_DetectionState A_detectionStatus;    //@ID 20783098
        T_DetectionType A_type;    //@ID 60540847
        P_LDM_Common::T_Duration A_lifeSpan;    //@ID 33812822
        P_LDM_Common::T_Int16 A_priority;    //@ID 261701171
        T_Trajectory A_trajectoryType;    //@ID 130758057
        sequence<P_Tactical_Sensor_PSM::T_Sensing_Method,15> A_method;    //@ID 21615206
        P_LDM_Common::T_Boolean A_spatialParametersAvailable;    //@ID 59484478
        T_Spatial_Info A_spatialInfo;    //@ID 266667200
        T_SuspensionCause A_suspensionCause;    //@ID 120918324
        P_LDM_Common::T_Descriptor A_designatedInfo; //@Optional
    //@ID 44045387
        P_LDM_Common::T_Byte A_numberOfDetectionMethods; //@Optional
    //@ID 165807565
        sequence<P_Tactical_Sensor_PSM::T_DetectingMethod,32> A_detectionMethods; //@Optional
    //@ID 87615255
        P_LDM_Common::T_Boolean A_snapshotAvailable;    //@ID 149581014
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    enum T_ThreatFamily {
        @default_literal
        L_ThreatFamily_UNKNOWN = 0,
        L_ThreatFamily_MARNAT = 1,
        L_ThreatFamily_TOLAR = 2,
        L_ThreatFamily_TANK_BULLET = 3,
        L_ThreatFamily_TANNAT = 4,
        L_ThreatFamily_OTHER = 5
    };
    //@Extensibility EXTENSIBLE_EXTENSIBILITY

    struct T_ThreatData {
        P_LDM_Common::T_DateTime A_threatID;    //@ID 241586546
        P_LDM_Common::T_ShortString A_threatType;    //@ID 42452415
        P_LDM_Common::T_Boolean A_isDetectedByEOS;    //@ID 119038996
        P_LDM_Common::T_Boolean A_isDetectedBySR;    //@ID 121962734
        P_LDM_Common::T_Boolean A_isDetectedByPearl;    //@ID 75379114
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    struct T_AronlodThreat {
        P_LDM_Common::T_AngleInRadians A_orientation;    //@ID 153422287
        P_LDM_Common::T_DistanceInMeters A_distance;    //@ID 178978473
        P_LDM_Common::T_Byte A_pencils;    //@ID 135574486
        sequence<P_Tactical_Sensor_PSM::T_ThreatData,32> A_threatPencils;    //@ID 162902902
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    struct C_Detection_Aps : C_Detection {
        P_LDM_Common::T_Duration A_timeToGo;    //@ID 16001726
        P_LDM_Common::T_Boolean A_affecting;    //@ID 63400329
        T_ThreatFamily A_threatFamily;    //@ID 71472818
        T_AronlodThreat A_threatAronlod; //@Optional
    //@ID 38827912
        P_LDM_Common::T_Descriptor A_actionStatus;    //@ID 170861292
        P_LDM_Common::T_Coordinate3D A_threatHitPoint;    //@ID 27758138
        P_LDM_Common::T_Descriptor A_threatRefinementInfo;    //@ID 140347192
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

}; // end of 'P_Tactical_Sensor_PSM' module

