module P_LDM_Common {
    typedef long T_Int32;

    typedef short T_Int16;

    struct T_Identifier {
        T_Int32 A_platformId;    //@ID 193125732
        T_Int16 A_systemId;    //@ID 226945837
        T_Int16 A_moduleId;    //@ID 98483598
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef long long T_Int64;

    struct T_DateTime {
        T_Int64 A_seconds;    //@ID 47523875
        T_Int32 A_nanoseconds;    //@ID 168751860
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

    typedef double T_Double;

    typedef T_Double T_DistanceInMeters;

    typedef T_DistanceInMeters T_Altitude;

    typedef T_Double T_AngleInRadians;

    typedef T_AngleInRadians T_Latitude;

    typedef T_AngleInRadians T_Longitude;

    struct T_Coordinate3D {
        T_Altitude A_altitude;    //@ID 143806669
        T_Latitude A_latitude;    //@ID 252288645
        T_Longitude A_longitude;    //@ID 249776067
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

}; // end of 'P_LDM_Common' module

module P_Navigation_PSM {
    struct C_Position {
        P_LDM_Common::T_Identifier A_sourceID; //@key
    //@ID 118386796
        P_LDM_Common::T_DateTime A_timeOfDataGeneration;    //@ID 234062147
        P_LDM_Common::T_Coordinate3D A_currentPosition;    //@ID 139922608
    };
    //@Extensibility MUTABLE_EXTENSIBILITY

}; // end of 'P_Navigation_PSM' module

